version: '3.0'
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: userName
      POSTGRES_DB: example_db
    ports:
      - "5555:5432"
  app:
    image: anshemonaev/fsi:latest
    container_name: app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/example_db
      SPRING_DATASOURCE_USERNAME: userName
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - postgres